import { useState } from 'react'
import './App.css'

const starterResume = {
  name: 'Maya Chen', role: 'Product Designer', location: 'Brooklyn, NY', email: 'maya.chen@email.com', phone: '(917) 555-0198',
  summary: 'Product designer with 6+ years of experience shaping clear, useful digital products for ambitious teams. I turn complex problems into intuitive experiences that people want to use.',
  experience: [
    { company: 'Northstar Labs', role: 'Senior Product Designer', dates: '2021 — Present', description: 'Led end-to-end design for the core platform, increasing activation by 28% and helping the team ship three major product launches.' },
    { company: 'Forma Studio', role: 'Product Designer', dates: '2018 — 2021', description: 'Partnered with founders and engineers to design digital products for 12 startups across fintech, health, and education.' },
  ],
  skills: ['Product strategy', 'UX research', 'Prototyping', 'Design systems', 'Figma', 'Webflow'], education: 'BFA, Communication Design · Parsons School of Design',
}

function App() {
  const [resume, setResume] = useState(starterResume)
  const [activeSection, setActiveSection] = useState('basics')
  const [isPolishing, setIsPolishing] = useState(false)
  const [polished, setPolished] = useState(false)
  const updateResume = (field, value) => setResume((current) => ({ ...current, [field]: value }))
  const updateExperience = (index, field, value) => setResume((current) => ({ ...current, experience: current.experience.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item) }))
  const polishWithAI = () => { setIsPolishing(true); window.setTimeout(() => { setResume((current) => ({ ...current, summary: 'Product designer with 6+ years of experience turning complex problems into intuitive, high-impact digital products. I partner with ambitious teams to build experiences that are clear, useful, and memorable.' })); setIsPolishing(false); setPolished(true) }, 700) }

  return (
    <div className="app-shell"><header className="topbar"><a className="brand" href="/" aria-label="Draftly home"><span className="brand-mark">✦</span> draftly</a><div className="header-center"><span className="status-dot" /> Autosaved just now</div><div className="header-actions"><button className="icon-button" title="Undo" aria-label="Undo">↶</button><button className="icon-button" title="Redo" aria-label="Redo">↷</button><button className="export-button" onClick={() => window.print()}>Export PDF <span>↗</span></button><div className="avatar">MC</div></div></header>
      <main className="workspace"><aside className="sidebar"><div className="side-heading"><div><p className="eyebrow">MY DOCUMENT</p><h1>Untitled resume</h1></div><button className="more-button" aria-label="More options">•••</button></div><div className="completion"><div className="completion-row"><span>Profile strength</span><strong>82%</strong></div><div className="progress"><span /></div><p>Looking good. A few details will make it even stronger.</p></div><nav className="section-nav" aria-label="Resume sections">{[['basics', '◌', 'Basics'], ['experience', '⌁', 'Experience'], ['skills', '✣', 'Skills'], ['education', '⌂', 'Education']].map(([id, icon, label]) => <button className={activeSection === id ? 'active' : ''} onClick={() => setActiveSection(id)} key={id}><span className="nav-icon">{icon}</span>{label}<span className="chevron">›</span></button>)}</nav><div className="ai-card"><div className="ai-card-title"><span className="sparkle">✦</span><strong>AI copilot</strong><span className="beta">BETA</span></div><p>Turn your experience into language that gets noticed.</p><button className="copilot-button" onClick={polishWithAI}>{isPolishing ? 'Polishing...' : 'Polish my resume'} <span>✦</span></button></div><div className="side-footer"><span className="help-icon">?</span><span>Need a hand?</span><span className="footer-arrow">↗</span></div></aside>
        <section className="editor-panel"><div className="panel-header"><div><p className="eyebrow">EDITING</p><h2>{activeSection === 'basics' ? 'Tell us about yourself' : activeSection[0].toUpperCase() + activeSection.slice(1)}</h2></div><button className="preview-toggle">Preview <span>⌄</span></button></div>{activeSection === 'basics' ? <div className="form-area"><div className="form-section"><div className="section-label"><span className="number">01</span><div><h3>Basics</h3><p>Start with the essentials.</p></div></div><div className="form-grid"><label className="wide">Full name<input value={resume.name} onChange={(event) => updateResume('name', event.target.value)} /></label><label>Target role<input value={resume.role} onChange={(event) => updateResume('role', event.target.value)} /></label><label>Location<input value={resume.location} onChange={(event) => updateResume('location', event.target.value)} /></label><label>Email<input value={resume.email} onChange={(event) => updateResume('email', event.target.value)} /></label><label>Phone<input value={resume.phone} onChange={(event) => updateResume('phone', event.target.value)} /></label></div></div><div className="form-section"><div className="section-label"><span className="number">02</span><div><h3>Professional summary</h3><p>A concise introduction that sounds like you.</p></div><span className="ai-label">✦ AI suggested</span></div><textarea value={resume.summary} onChange={(event) => updateResume('summary', event.target.value)} rows="5" /><div className="textarea-footer"><span>{resume.summary.length} / 320</span><button onClick={polishWithAI}>✦ Improve with AI</button></div></div><div className="form-section"><div className="section-label"><span className="number">03</span><div><h3>Experience</h3><p>Show the work you are proud of.</p></div><button className="add-button">＋ Add role</button></div>{resume.experience.map((item, index) => <div className="experience-item" key={item.company}><div className="experience-top"><strong>{item.company}</strong><button aria-label={`Remove ${item.company}`}>×</button></div><div className="form-grid"><label>Role<input value={item.role} onChange={(event) => updateExperience(index, 'role', event.target.value)} /></label><label>Dates<input value={item.dates} onChange={(event) => updateExperience(index, 'dates', event.target.value)} /></label></div><label>Description<textarea value={item.description} onChange={(event) => updateExperience(index, 'description', event.target.value)} rows="3" /></label></div>)}</div></div> : <div className="empty-section"><span className="empty-symbol">✦</span><h3>{activeSection === 'experience' ? 'Your experience, your story.' : activeSection === 'skills' ? 'The tools that make you you.' : 'Every great story has a beginning.'}</h3><p>Jump back to Basics to see your live document, or keep shaping this section here.</p><button onClick={() => setActiveSection('basics')}>Back to basics</button></div>}</section>
        <section className="preview-panel"><div className="preview-top"><span>LIVE PREVIEW</span><div><button className="preview-icon" title="Zoom out">−</button><span className="zoom">100%</span><button className="preview-icon" title="Zoom in">＋</button></div></div><div className="paper"><div className="paper-header"><div><h2>{resume.name}</h2><p>{resume.role}</p></div><div className="contact"><span>{resume.location}</span><span>{resume.email}</span><span>{resume.phone}</span></div></div><div className="paper-rule" /><div className="paper-section"><h3>Profile</h3><p>{resume.summary}</p></div><div className="paper-section"><h3>Experience</h3>{resume.experience.map((item) => <div className="paper-experience" key={item.company}><div className="paper-job"><strong>{item.role}</strong><span>{item.dates}</span></div><p>{item.company}</p><div>{item.description}</div></div>)}</div><div className="paper-section"><h3>Skills</h3><div className="skill-list">{resume.skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div><div className="paper-section"><h3>Education</h3><p>{resume.education}</p></div><div className="paper-footer">maya-chen.com <span>•</span> crafted with draftly</div></div><div className="preview-note"><div className="note-icon">✦</div><div><strong>{polished ? 'Nice work. Your summary is sharper.' : 'Make your first impression count.'}</strong><p>{polished ? 'The new version leads with your value and keeps your voice.' : 'Recruiters spend 7 seconds on a resume. Let’s make yours memorable.'}</p></div></div></section></main><div className="toast"><span className="toast-check">✓</span> Your changes are saved</div></div>
  )
}

export default App
